/**
 * Centralized mapping for module codes used in access control.
 */
export const MODULE_CODES = {
  DASHBOARD: "DASHBOARD",
  PRODUCT_MANAGER: "PRODUCT_MANAGER",
  ROLE_MANAGER: "ROLE_MANAGER",
  WAREHOUSE_MANAGER: "WAREHOUSE_MANAGER",
  USER_MANAGER: "USER_MANAGER",
  SUPPORT_MANAGER: "SUPPORT_MANAGER",
  POST_MANAGER: "POST_MANAGER",
  SETTINGS_MANAGER: "SETTINGS_MANAGER",
};

