/**
 * File: roleConstants.js
 * Purpose: Constants for roles, permissions, and modules that are fixed in the system.
 */

export const ROLE_CODES = [
  "ADMIN",
  "CONTENT_CREATOR",
  "CUSTOMER_CARE",
  "STORAGE_STAFF",
  "CUSTOMER"
];

export const PERMISSION_CODES = [
  "CREATE",
  "EDIT",
  "DELETE",
  "VIEW_LIST",
  "VIEW_DETAIL",
  "ACCESS"
];

export const MODULE_CODES_LIST = [
  "PRODUCT_MANAGER",
  "USER_MANAGER",
  "SUPPORT_MANAGER",
  "POST_MANAGER",
  "ROLE_MANAGER",
  "SETTINGS_MANAGER",
  "WAREHOUSE_MANAGER"
];

export const MODULE_CODES = {
  PRODUCT_MANAGER: "PRODUCT_MANAGER",
  USER_MANAGER: "USER_MANAGER",
  SUPPORT_MANAGER: "SUPPORT_MANAGER",
  POST_MANAGER: "POST_MANAGER",
  ROLE_MANAGER: "ROLE_MANAGER",
  SETTINGS_MANAGER: "SETTINGS_MANAGER",
  WAREHOUSE_MANAGER: "WAREHOUSE_MANAGER"
};

